apiVersion: 1

datasources:
  - name: Pooli Usage MySQL
    uid: mysql-usage-ds
    type: mysql
    access: proxy
    url: ${GF_USAGE_MYSQL_HOST}:${GF_USAGE_MYSQL_PORT}
    user: ${GF_USAGE_MYSQL_USER}
    editable: true
    isDefault: false
    jsonData:
      database: ${GF_USAGE_MYSQL_DATABASE}
      maxOpenConns: 20
      maxIdleConns: 10
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
    secureJsonData:
      password: ${GF_USAGE_MYSQL_PASSWORD}
