apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord-webhook
    receivers:
      - uid: discord-webhook-uid
        type: discord
        settings:
          url: $DISCORD_WEBHOOK_URL
          title: '{{ template "discord.logs.title" . }}'
          message: '{{ template "discord.logs.message" . }}'
