apiVersion: 1

groups:
  - orgId: 1
    name: loki-alert-group
    folder: Loki Alerts
    interval: 30s   # 알람 체크 주기

    rules:
      - uid: loki_error_alert
        title: Loki ERROR detected
        condition: C
        for: 1m   # 1분 동안 조건 유지되면 알람

        noDataState: OK
        execErrState: Alerting

        data:
          - refId: A
            datasourceUid: loki-ds   # Loki datasource UID (Grafana datasource 설정에서 확인 가능)
            relativeTimeRange:
              from: 120
              to: 0
            model:
              expr: |
                 count_over_time(
                 {job=~"pooli-be|traffic-generator"}
                  | json
                  | level=~"(?i)error|FATAL|WARN"
                  [1m]
                 )
                
                
                #count_over_time({job=~"system|monitoring"} |= "ERROR" [1m])
              queryType: instant
              refId: A

          - refId: C
            datasourceUid: __expr__
            model:
              type: threshold
              expression: A
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt   # 0보다 크면 alert
                  operator:
                    type: and
                  query:
                    params: ["A"]
                  reducer:
                    type: last

        annotations:
          summary: "ERROR log detected"
          description: |
            {{ if gt (len .Value) 0 }}
            최근 {{ len .Value }}건 오류:
            {{- range $i, $v := .Value }}
              - {{ $v }}
            {{- end }}
            {{ else }}
            오류 없음
            {{ end }}
          errorCode: "{{ .Labels.errorCode }}"

        labels:
          severity: critical
