apiVersion: 1

templates:
  - orgId: 1
    name: discord.custom.title
    template: |
      {{ if eq .Status "firing" }}
      [FIRING] {{ .CommonLabels.alertname }} ({{ .CommonLabels.severity }})
      {{ else }}
      [RESOLVED] {{ .CommonLabels.alertname }} ({{ .CommonLabels.severity }})
      {{ end }}

  - orgId: 1
    name: discord.custom.message
    template: |
      상태: {{ .Status }}
      알람 수: firing={{ len .Alerts.Firing }}, resolved={{ len .Alerts.Resolved }}
      심각도: {{ .CommonLabels.severity }}
      요약: {{ .CommonAnnotations.summary }}
      설명: {{ .CommonAnnotations.description }}

      {{ if gt (len .Alerts.Firing) 0 }}
      🔹 상세 로그:
      {{ range .Alerts.Firing }}
      - 에러 코드: {{ .Annotations.errorCode }}
        로그 메시지: {{ if gt (len .Annotations.description) 200 }}
          {{ slice .Annotations.description 0 200 }}...(truncated)
        {{ else }}
          {{ .Annotations.description }}
        {{ end }}
        로그 값: 
        {{- range .Value }}
           - {{ .var }}: {{ .value }}
        {{- end }}
      {{ end }}
      {{ end }}
      🔗 Grafana 확인:
        {{ .ExternalURL }}
