apiVersion: 1

policies:
  - orgId: 1
    receiver: discord-webhook
    group_by:
      - alertname
      - severity
    routes:
      - receiver: discord-webhook
        object_matchers:
          - ['severity', '=', 'critical']
