global:
  scrape_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "pooli-instance"
    static_configs:
      - targets:
          - "10.0.135.58:9100"
        labels:
          instance: db-server
      - targets:
          - "10.0.132.120:9100"
        labels:
          instance: api-server
      - targets:
          - "10.0.132.194:9100"
        labels:
          instance: redis-session-sever
      - targets:
          - "10.0.143.8:9100"
        labels:
          instance: mongodb-server
      - targets:
          - "10.0.129.17:9100"
        labels:
          instance: redis-cache-server
      - targets:
          - "10.0.134.86:9100"
        labels:
          instance: redis-stream-server
      - targets:
          - "10.0.137.213:9100"
        labels:
          instance: traffic-server



  - job_name: "pooli-be"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "10.0.132.120:8080"
        labels:
          instance: api-server
          application: pooli-be
          env: production
      - targets:
          - "10.0.137.213:8080"
        labels:
          instance: traffic-server
          application: pooli-be
          env: production


